name: binder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - xmltodict
  - requests
  - lxml
  - pip
  - jupyter
  - ipykernel
  - python-dotenv
  - pip:
    - python-dotenv

postBuild:
  - ./start