#!/bin/bash
set +H  # Disable history expansion
# Write the UNDL_API_KEY to a .env file if it's set
if [ -n "$UNDL_API_KEY" ]; then
  echo "UNDL_API_KEY=${UNDL_API_KEY}" > .env
else
  echo "UNDL_API_KEY is not set!"
  echo "UNDL_API_KEY=" > .env
fi
exec "$@"
